---
- include_vars:
    file: ../../group_vars/{{ inventory_hostname }}/{{ container }}

- set_fact:
    docker_compose_content: "{{ lookup('template', '../../templates/docker-compose.yml.j2') }}"

- name: Add container info in docker-compose file
  blockinfile:
    path: "{{ docker_compose_file }}"
    marker: "# {mark} {{ container }} container info"
    content: "{{ docker_compose_content }}"
