---
- hosts: leaf[0]:spine[0]
  become: yes
  ignore_errors: yes

  tasks:
    - name: Stop and remove any existing docker containers
      shell: "{{ item }}"
      with_items:
      - "docker stop $(docker ps -a -q)"
      - "docker rm $(docker ps -a -q)"

    - name: Remove docker-compose files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - "~/docker_move.sh"
      - "{{ docker_compose_file }}"

    - shell: rm -rf ~/volumes/quagga/*

    - shell: "ip netns | xargs -I {} sudo ip netns delete {}"

    - name: Restore backup of /etc/network/interfaces
      copy:
        src: "{{ network_interfaces_file_bck }}"
        dest: "{{ network_interfaces_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ network_interfaces_file_bck }}"
        state: absent

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'rmmod platina-mk1'
      - 'modprobe platina-mk1 provision=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1'
      - 'ifdown -a --allow vnet'
      - 'ifup -a --allow vnet'
      - 'goes restart'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10


- hosts: leaf[0]
  become: true
  tasks:
    - name: Uninstall dhcp
      apt:
        name: isc-dhcp-server
        state: absent
        purge: yes
        autoremove: yes
