---
- hosts: server_emulator
  become: true

  tasks:
  - command: "date +%Y%m%d%T"
    register: start_time

  - set_fact:
     hash_name: "32_blackhole_10g_portprov_route_basic_{{ start_time.stdout }}"
     start_time: "{{ start_time.stdout }}"

- hosts: leaf:spine
  become: true
  tasks:
    - name: Copy port provisioned interfaces_10g_cr_fec_none_autoneg_off_lanes_1_count_4 file to /etc/network/interfaces
      template:
          src: "../../files/{{ inventory_hostname }}/interfaces_10g_cr_fec_none_autoneg_off_lanes_1_count_4"
          dest: "{{ network_interfaces_file }}"
      when: not dry_run

    - name: Copy goesd-platina-mk1-modprobe.conf file
      template:
          src: "../../files/goesd-platina-mk1-modprobe.conf_lane1_count4"
          dest: "{{ goesd_modprobe_file }}"
      when: not dry_run

    - name: Update interfaces file for fiber ports
      test_fiber_ports:
        cmd : "4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1"
      register: fmodule_out

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10
      when: not dry_run

    - name: Restart goes
      command: "{{ item }}"
      with_items:
      - 'rmmod platina-mk1'
      - "modprobe platina-mk1 provision={{ fmodule_out.hash_dict['command'] }}"
      - 'ifdown -a --allow vnet'
      - 'ifup -a --allow vnet'
      - 'goes restart'
      when: not dry_run

    - name: Wait for GoES to come up
      pause:
        seconds: 10

- hosts: leaf[1]
  become: true
  tasks:
    - name: Copy black hole interfaces interfaces_black_hole_10g_cr_fec_none_autoneg_off_lanes_1_count_4 to /etc/network/interfaces
      template:
        src: "../../files/{{ inventory_hostname }}/interfaces_black_hole_32_10g_cr_fec_none_autoneg_off_lanes_1_count_4"
        dest: "{{ network_interfaces_file }}"

    - name: Execute commands
      command: "{{ item }}"
      with_items:
          - 'rmmod platina-mk1'
          - "modprobe platina-mk1 provision={{ fmodule_out.hash_dict['command'] }}"
          - 'ifdown -a --allow vnet'
          - 'ifup -a --allow vnet'
          - 'goes restart'
      ignore_errors: yes

    - name: Wait for GoES to come up
      pause:
        seconds: 10


    - name: Verify black hole addition to tables
      verify_blackhole_route:
          switch_name: "{{ inventory_hostname }}"
          eth_list: "5"
          subnet_mask: "32"
          spine_list: "{{ groups['spine'] }}"
          leaf_list: "{{ groups['leaf']}}"
          hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
          is_subports: True
          log_dir_path: "{{ blackhole_route_dir }}"
      register: module_out
      when: not dry_run

    - file:
          path: "{{ blackhole_route_dir }}"
          state: directory
      when: not dry_run

    - name: Power Cycle redis DB
      command: "redis-cli -h {{ bmc_redis_ip }} hset platina-mk1-bmc psu.powercycle true"
      when: not dry_run

    - name: waiting for switch to come back after powercycle
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15
      when: not dry_run

    - name: Reverify black hole addition to tables
      verify_blackhole_route:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "5"
        subnet_mask: "32"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        is_subports: True
        log_dir_path: "{{ blackhole_route_dir }}"
      register: module_out
      when: not dry_run

    - command: "date +%Y%m%d%T"
      register: end_time
      when: not dry_run
      ignore_errors: yes

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs
      when: not dry_run

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
              hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
              start_time: "{{ hostvars['server_emulator']['start_time'] }}"
              end_time: "{{ end_time.stdout }}"
              hash_dict: "{{ module_out.hash_dict }}"
              log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1
      ignore_errors: yes
      when: not dry_run

- include: black_hole_reset.yml
  when:
    - reset_config
    - not dry_run


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result
      when: not dry_run

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"
      when: not dry_run

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"
      when: not dry_run

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "{{ hash_name }}: {{ result.result_status }}"
      when: not dry_run

- hosts: leaf:spine
  become: true
  gather_facts: no
  tasks:
    - include: ../../playbooks/get_goes_status.yml start_time={{ hostvars['server_emulator']['start_time'] }} hash_name={{ hostvars['server_emulator']['hash_name'] }}
      when: not dry_run
      ignore_errors: yes

