---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - name: Restore backup of /etc/frr/ospfd.conf
      copy:
        src: "{{ frr_ospf_conf_file_bck }}"
        dest: "{{ frr_ospf_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ frr_ospf_conf_file_bck }}"
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restore backup of /etc/network/interfaces
      copy:
        src: "{{ network_interfaces_file_bck }}"
        dest: "{{ network_interfaces_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ network_interfaces_file_bck }}"
        state: absent

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'ifdown -a --allow vnet'
      - 'ifup -a --allow vnet'
      - 'goes restart'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10
