---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version
      when: not dry_run

    - debug:
        var: kernel_version.stdout_lines
      when: not dry_run

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "quagga_multipath_routing_ospf_with_port_provision_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - file:
        path: "{{ ospf_log_dir }}"
        state: directory
      when: not dry_run

    - name: Copy port provisioned interfaces_10g_cr_fec_none_autoneg_off_lanes_1_count_4 file to /etc/network/interfaces
      template:
        src: "../../files/{{ inventory_hostname }}/interfaces_10g_cr_fec_none_autoneg_off_lanes_1_count_4"
        dest: "{{ network_interfaces_file }}"
      when: not dry_run

    - name: Copy goesd-platina-mk1-modprobe.conf file
      template:
        src: "../../files/goesd-platina-mk1-modprobe.conf_lane1_count4"
        dest: "{{ goesd_modprobe_file }}"
      when: not dry_run

    - name: Update interfaces file for fiber ports
      test_fiber_ports:
        cmd : "4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1"
      register: fmodule_out

    - name: Restart goes
      command: "{{ item }}"
      with_items:
      - 'rmmod platina-mk1'
      - "modprobe platina-mk1 provision={{ fmodule_out.hash_dict['command'] }}"
      - 'ifdown -a --allow vnet'
      - 'ifup -a --allow vnet'
      - 'goes restart'
      when: not dry_run

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10
      when: not dry_run

    - set_fact:
        commands: "{{ item }}"
      with_items:
      - 'rmmod platina-mk1'
      - "modprobe platina-mk1 provision={{ fmodule_out.hash_dict['command'] }}"
      - 'ifdown -a --allow vnet'
      - 'ifup -a --allow vnet'
      - 'goes restart'
      when: dry_run

    - name: Verify media, speed and fec values
      test_port_links:
        switch_name: "{{ inventory_hostname }}"
        speed: "10g"
        media: "copper"
        fec: "none"
        autoneg: "off"
        is_subports: True
        f_ports: "{{ fmodule_out.hash_dict['eth_list'] }}"
        platina_redis_channel: "{{ platina_redis_channel }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ port_provision_log_dir }}"
      register: module_out
      when: not dry_run

    - name: Verify media, speed and fec values
      test_port_links:
        switch_name: "{{ inventory_hostname }}"
        speed: "10g"
        media: "copper"
        fec: "none"
        autoneg: "off"
        is_subports: True
        f_ports: "{{ fmodule_out.hash_dict['eth_list'] }}"
        platina_redis_channel: "{{ platina_redis_channel }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ port_provision_log_dir }}"
        dry_run_mode: "{{ dry_run }}"
      register: dry_run_out
      delegate_to: 127.0.0.1
      when: dry_run

    - set_fact:
        dry_run_cmds: "{{ dry_run_out.cmds }}"
      when: dry_run
 
    - command: "date +%Y%m%d%T"
      register: end_time
      when: not dry_run

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs
      when: not dry_run

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1
      ignore_errors: yes
      when: not dry_run

    - copy:
        src: "../../files/show_tech.py"
        dest: /tmp/show_tech.py
        mode: 0755
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - command: "/tmp/./show_tech.py --path /var/log/show_tech/ --hash_name {{ hostvars['server_emulator']['hash_name'] }}"
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - file:
        path: /tmp/show_tech.py
        state: absent
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes


- hosts: spine
  become: true
  tasks:
    - name: Initiate iperf servers
      shell: "iperf -s &"
      when: not dry_run

    - set_fact:
        iperf_cmd: "iperf -s &"
      when: dry_run


- hosts: leaf[0]
  become: true
  tasks:
    - name: Initiate iperf client and verify traffic
      verify_iperf_traffic:
        switch_name: "{{ inventory_hostname }}"
        eth_ips_last_octet: "31,32"
        is_subports: True
        f_ports: "{{ fmodule_out.hash_dict['eth_list'] }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ port_provision_log_dir }}"
      register: module_out
      when: not dry_run

    - name: Initiate iperf client and verify traffic
      verify_iperf_traffic:
        switch_name: "{{ inventory_hostname }}"
        eth_ips_last_octet: "31,32"
        is_subports: True
        f_ports: "{{ fmodule_out.hash_dict['eth_list'] }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ port_provision_log_dir }}"
        dry_run_mode: "{{ dry_run }}"
      register: idry_run_out
      delegate_to: 127.0.0.1
      when: dry_run
  
    - set_fact:
        idry_run_cmds: "{{ idry_run_out.cmds }}"
      when: dry_run

    - command: "date +%Y%m%d%T"
      register: end_time
      when: not dry_run

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs
      when: not dry_run

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1
      ignore_errors: yes
      when: not dry_run

    - copy:
        src: "../../files/show_tech.py"
        dest: /tmp/show_tech.py
        mode: 0755
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - command: "/tmp/./show_tech.py --path /var/log/show_tech/ --hash_name {{ hostvars['server_emulator']['hash_name'] }}"
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - file:
        path: /tmp/show_tech.py
        state: absent
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/quagga/ospfd.conf
      copy:
        src: "{{ quagga_ospf_conf_file }}"
        dest: "{{ quagga_ospf_conf_file_bck }}"
        remote_src: true

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Add ospf config in /etc/quagga/ospfd.conf
      blockinfile:
        path: "{{ quagga_ospf_conf_file }}"
        marker: ""
        block: "{{ lookup('file', '../../files/{{inventory_hostname}}/ospf_multipath_with_port_provision.conf') }}"
        insertbefore: "^line vty"

    - name: Restart quagga service
      service:
        name: quagga
        state: restarted

    - name: Verify ospf configuration
      test_multipath_routing_ospf_with_port_provision:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "3-1,3-4,19-1,19-4"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        stage: "initial stage"
        is_ping: True
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out


- hosts: spine
  become: true
  tasks:
    - name: Bring down interface on spines
      command: "ifconfig xeth{{ item }} down"
      with_items:
        - 3-4
        - 19-1


- hosts: leaf:spine
  become: true
  tasks:
    - name: Wait few secs
      pause:
        seconds: 20

    - name: Verify ospf configuration
      test_multipath_routing_ospf_with_port_provision:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "3-1,3-4,19-1,19-4"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        interface: "3-4,19-1"
        stage: "after bringing interface down"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out


- hosts: spine
  become: true
  tasks:
    - name: Bring up interface on spines
      command: 'ifconfig xeth{{ item }} up'
      with_items:
        - 3-4
        - 19-1


- hosts: leaf:spine
  become: true
  tasks:
    - name: Wait few secs
      pause:
        seconds: 20

    - name: Verify ospf configuration
      test_multipath_routing_ospf_with_port_provision:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "3-1,3-4,19-1,19-4"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        stage: "after bringing interface up"
        interface: "3-4,19-1"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out


- hosts: leaf:spine
  become: true
  tasks:
    - name: Execute commands
      command: "goes restart"

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10

    - name: Verify ospf configuration
      test_multipath_routing_ospf_with_port_provision:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "3-1,3-4,19-1,19-4"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        stage: "after restarting goes"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out

    - name: reboot the switch
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for switch to come back after reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Wait few secs
      pause:
        seconds: 60

    - name: Verify ospf configuration
      test_multipath_routing_ospf_with_port_provision:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "3-1,3-4,19-1,19-4"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        stage: "after rebooting the invader"
        is_ping: True
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - copy:
        src: "../../files/show_tech.py"
        dest: /tmp/show_tech.py
        mode: 0755
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - command: "/tmp/./show_tech.py --path /var/log/show_tech/ --hash_name {{ hostvars['server_emulator']['hash_name'] }}"
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - file:
        path: /tmp/show_tech.py
        state: absent
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - include: ../../playbooks/get_goes_version_and_tags.yml


- include: multipath_routing_2_ospf_with_port_provision_reset.yml
  when: reset_config


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "{{ hash_name }}: {{ result.result_status }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml start_time={{ hostvars['server_emulator']['start_time'] }} hash_name={{ hostvars['server_emulator']['hash_name'] }}

