---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version

    - debug:
        var: kernel_version.stdout_lines


- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "quagga_ospf_multipath_routing_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/quagga/ospfd.conf
      copy:
        src: "{{ quagga_ospf_conf_file }}"
        dest: "{{ quagga_ospf_conf_file_bck }}"
        remote_src: true

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Add ospf config in /etc/quagga/ospfd.conf
      blockinfile:
        path: "{{ quagga_ospf_conf_file }}"
        marker: ""
        block: "{{ lookup('file', '../../files/{{inventory_hostname}}/ospf_multipath.conf') }}"
        insertbefore: "^line vty"

    - name: Restart quagga service
      service:
        name: quagga
        state: restarted

    - name: Wait few secs for ospf to establish communication
      pause:
        seconds: 35

    - file:
        path: "{{ ospf_log_dir }}"
        state: directory

    - name: Verify ospf configuration
      test_ospf_multipath:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "3,7,19"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        stage: "initial stage"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out


- hosts: spine
  become: true
  tasks:
    - name: Bring down interface on spines
      command: 'ifconfig xeth3 down'


- hosts: leaf:spine
  become: true
  tasks:
    - name: Wait few secs
      pause:
        seconds: 20

    - name: Verify ospf configuration
      test_ospf_multipath:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "3,7,19"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        interface: "3"
        stage: "after bringing interface down"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out


- hosts: spine
  become: true
  tasks:
    - name: Bring up interface on spines
      command: 'ifconfig xeth3 up'


- hosts: leaf:spine
  become: true
  tasks:
    - name: Wait few secs
      pause:
        seconds: 20

    - name: Execute commands
      command: "goes restart"

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10

    - name: Verify ospf configuration
      test_ospf_multipath:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "3,7,19"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        stage: "after restarting goes"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out

    - name: reboot the switch
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for switch to come back after reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Wait few secs
      pause:
        seconds: 60

    - name: Verify ospf configuration
      test_ospf_multipath:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "3,7,19"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        stage: "after rebooting the invader"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - copy:
        src: "../../files/show_tech.py"
        dest: /tmp/show_tech.py
        mode: 0755
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - command: "/tmp/./show_tech.py --path /var/log/show_tech/ --hash_name {{ hostvars['server_emulator']['hash_name'] }}"
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - file:
        path: /tmp/show_tech.py
        state: absent
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - include: ../../playbooks/get_goes_version_and_tags.yml


- include: quagga_ospf_multipath_routing_reset.yml
  when: reset_config


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "{{ hash_name }}: {{ result.result_status }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml start_time={{ hostvars['server_emulator']['start_time'] }} hash_name={{ hostvars['server_emulator']['hash_name'] }}
