---

- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/quagga/ospfd.conf
      copy:
        src: "{{ quagga_ospf_conf_file_bck }}"
        dest: "{{ quagga_ospf_conf_file }}"
        remote_src: true

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'goes restart'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10

    - name: Remove backup file
      file:
        path: "{{ quagga_ospf_conf_file_bck }}"
        state: absent
