- name: add/create dummy0 interface
  shell: ip link add dummy0 type dummy
  register: cmd_output
- debug:
    var: cmd_output
    verbosity: 2

- name: check dummy0 exists
  shell: ip link show dummy0
  register: cmd_output
- debug:
    var: cmd_output
    verbosity: 2
- assert:
    that:
      - "'dummy0:' in cmd_output.stdout"

- name: set ip address
  shell: ip address add 5.5.5.5/32 dev dummy0
  register: cmd_output
- debug:
    var: cmd_output
    verbosity: 2
