---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version
      when: not dry_run

    - debug:
        var: kernel_version.stdout_lines
      when: not dry_run


- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "ntp_reboot_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf[1]
  become: true
  tasks:
    - file:
        path: "{{ ntp_log_dir }}"
        state: directory
      when: not dry_run

    - name: Check goes status
      restart_and_check_goes_status:
        is_restart: False
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ntp_log_dir }}"
      register: module_out

    - name: Check ntp status
      ntp_status:
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ntp_log_dir }}"
      register: module_out

    - name: Take backup of /etc/ntp.conf
      copy:
        src: "{{ ntp_conf_file }}"
        dest: "{{ ntp_conf_file_bck }}"
        remote_src: true
      when: not dry_run

    - name: Add ntp config in /etc/ntp.conf
      copy:
        src: ../../files/{{inventory_hostname}}/ntp.conf
        dest: "{{ ntp_conf_file }}"
      when: not dry_run

    - name: Restart ntp
      service:
        name: ntp
        state: restarted
      when: not dry_run

    - name: Wait some time
      pause:
        seconds: "{{ package_delay }}"
      when: not dry_run

    - name: Verify ntp working
      test_ntp:
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ntp_log_dir }}"
        stage: "before goes restart"
      register: module_out

    - set_fact:
        prev_date: "{{ module_out.hash_dict['date'] }}"

    - name: Restart goes
      service:
        name: goes
        state: restarted
      when: not dry_run

    - name: Wait some time
      pause:
        seconds: "{{ package_delay }}"
      when: not dry_run

    - name: Verify ntp working
      test_ntp:
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ntp_log_dir }}"
      register: module_out

    - name: Reboot invader
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for switch to come back after reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=60 timeout=300 connect_timeout=15

    - name: Check goes status
      restart_and_check_goes_status:
        is_restart: False
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ntp_log_dir }}"
      register: module_out

    - name: Verify ntp working
      test_ntp:
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ntp_log_dir }}"
      register: module_out

    - name: Restore backup of /etc/ntp.conf
      copy:
        src: "{{ ntp_conf_file_bck }}"
        dest: "{{ ntp_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ ntp_conf_file_bck }}"
        state: absent

    - name: Restart ntp
      service:
        name: ntp
        state: restarted
      when: not dry_run

    - name: Wait some time
      pause:
        seconds: "{{ package_delay }}"
      when: not dry_run

    - name: Verify ntp working
      test_ntp:
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ntp_log_dir }}"
        stage: "restore"
        prev_val: "{{ prev_date }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time
      when: not dry_run

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs
      when: not dry_run

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1
      ignore_errors: yes
      when: not dry_run

    - copy:
        src: "../../files/show_tech.py"
        dest: /tmp/show_tech.py
        mode: 0755
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - command: "/tmp/./show_tech.py --path /var/log/show_tech/ --hash_name {{ hostvars['server_emulator']['hash_name'] }}"
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - file:
        path: /tmp/show_tech.py
        state: absent
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - include: ../../playbooks/get_goes_version_and_tags.yml
      when: not dry_run


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result
      when: not dry_run

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"
      when: not dry_run

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"
      when: not dry_run

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "{{ hash_name }}: {{ result.result_status }}"
      when: not dry_run


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml start_time={{ hostvars['server_emulator']['start_time'] }} hash_name={{ hostvars['server_emulator']['hash_name'] }}
      when: not dry_run







