---
- name: Stop quagga service
  service:
    name: quagga
    state: stopped

- name: Quagga Uninstallation
  apt:
    name: quagga
    state: absent
    force: yes
    autoremove: yes
    purge: yes
