---

- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/quagga/zebra.conf
      copy:
        src: "{{ quagga_zebra_conf_file_bck }}"
        dest: "{{ quagga_zebra_conf_file }}"
        remote_src: true
      when: not dry_run

    - name: Remove zebra backup file
      file:
        path: "{{ quagga_zebra_conf_file_bck }}"
        state: absent
      when: not dry_run
      
    - name: Restore backup of /etc/quagga/bgpd.conf
      copy:
        src: "{{ quagga_bgp_conf_file_bck }}"
        dest: "{{ quagga_bgp_conf_file }}"
        remote_src: true
      when: not dry_run

    - name: Remove bgp backup file
      file:
        path: "{{ quagga_bgp_conf_file_bck }}"
        state: absent
      when: not dry_run

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'goes restart'
      when: not dry_run

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10
      when: not dry_run

    - name: Goes status
      command: goes status
      register: result
      retries: "{{ goes_retry }}"
      delay: "{{ goes_delay }}"
      until: result.rc == 0
      when: not dry_run

    - name: Restart quagga
      service:
        name: quagga
        state: restarted
      when: not dry_run
