---

- name: reboot the switch
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: waiting for switch to come back after reboot
  local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15

- name: Verify SDA partition
  verify_sda_partition:
    switch_name: "{{ inventory_hostname }}"
    hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
    log_dir_path: "{{ system_restartability_log_dir }}"
  register: module_out
  when: not dry_run
