---

- hosts: leaf:spine
  become: true
  tasks:
    - name: Remove config file
      file:
        path: "{{ gobgp_bgp_conf_file }}"
        state: absent
      when: not dry_run

    - name: Remove advertise route
      add_remove_route:
        switch_name: "{{ inventory_hostname }}"
        remove: True
      when: not dry_run

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'goes restart'
      when: not dry_run

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10
      when: not dry_run

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"
      when: not dry_run
