---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - name: Remove config file
      file:
        path: "{{ gobgp_bgp_conf_file }}"
        state: absent
      when: not dry_run

    - name: Restore backup of /etc/quagga/zebra.conf
      copy:
        src: "{{ quagga_zebra_conf_file_bck }}"
        dest: "{{ quagga_zebra_conf_file }}"
        remote_src: true
      when: not dry_run

    - name: Remove backup file
      file:
        path: "{{ quagga_zebra_conf_file_bck }}"
        state: absent
      when: not dry_run

    - name: Delete advertised routes
      command: "gobgp global rib -a ipv4 del 192.168.{{item}}.1/32"
      with_items:
      - 29
      - 30
      - 31
      - 32
      - 42
      - 43
      - 44
      - 45
      when: not dry_run

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'goes restart'
      when: not dry_run

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10
      when: not dry_run

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"
      when: not dry_run
