---

- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/quagga/bgpd.conf
      copy:
        src: "{{ quagga_bgp_conf_file_bck }}"
        dest: "{{ quagga_bgp_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ quagga_bgp_conf_file_bck }}"
        state: absent


- hosts: leaf:spine
  become: true
  tasks:
    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'goes restart'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10

    - name: Restart quagga
      service:
        name: quagga
        state: restarted
