---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version

    - debug:
        var: kernel_version.stdout_lines


- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - name: Copy bmc_upgrade script
      template:
        src: ../../templates/bmc_upgrade.sh
        dest: "/tmp/bmc_upgrade_{{ inventory_hostname }}.sh"
        mode: 0755
      delegate_to: 127.0.0.1

    - name: Run bmc_upgrade script
      shell: "./bmc_upgrade_{{ inventory_hostname }}.sh"
      args:
        chdir: /tmp/
      register: upgrade
      delegate_to: 127.0.0.1

    - debug:
        var: upgrade.stdout_lines

    - name: Remove bmc_upgrade script
      file:
        path: "/tmp/bmc_upgrade_{{ inventory_hostname }}.sh"
        state: absent
      delegate_to: 127.0.0.1
 
     
    - debug:
        msg: "BMC latest version already installed"
      when: upgrade.stdout.find('not newer') != -1

    - debug:
        msg: "BMC successfully Upgraded"
      when: upgrade.stdout.find('Starting kernel') != -1
      
    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "BMC Upgrade: BMC latest version already installed"
      delegate_to: 127.0.0.1
      when: upgrade.stdout.find('not newer') != -1

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "BMC Upgrade: BMC successfully Upgraded"
      delegate_to: 127.0.0.1
      when: upgrade.stdout.find('Starting kernel') != -1


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml

    - name: Verify link status b/w invaders
      verify_links:
        switch_name: "{{ inventory_hostname }}"
        leaf_list: "{{ groups['leaf'] }}"
        eth_list: "1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31"
        platina_redis_channel: "{{ platina_redis_channel }}"
      register: module_out

    - name: Print Link Status
      debug:
        var: module_out

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "Links Status {{ inventory_hostname }}: {{ module_out.msg }}"
      delegate_to: 127.0.0.1

