---

# Downgrade BMC 
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

# Downgrade BMC
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

# Downgrade BMC
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

# Downgrade BMC
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

# Downgrade BMC
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

# Downgrade BMC
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

# Downgrade BMC
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

# Downgrade BMC
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

# Downgrade BMC
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

# Downgrade BMC
- include: playbooks/upgrade/bmc_downgrade.yml

# Upgrade BMC
- include: playbooks/upgrade/bmc_upgrade.yml

