---

# Uninstall packages stack
- include: playbooks/installation/uninstall_packages.yml


# Reset invaders
- include: playbooks/master_reset_invaders.yml


# Run all vlan test cases
- include: playbooks/ntp/ntp_powercycle.yml

- include: playbooks/ntp/ntp_reboot.yml

