---

- hosts: leaf:spine
  become: yes
  ignore_errors: yes
  tasks:
    - name: Restore backup of /etc/quagga/ospfd.conf
      copy:
        src: "{{ quagga_ospf_conf_file_bck }}"
        dest: "{{ quagga_ospf_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ quagga_ospf_conf_file_bck }}"
        state: absent

    - name: Restart quagga
      service:
        name: quagga
        state: restarted

    - name: Copy default network interfaces file
      template:
        src: "../../files/{{inventory_hostname}}/network_interfaces_master"
        dest: "{{ network_interfaces_file }}"

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'ifdown -a --allow vnet'
      - 'ifup -a --allow vnet'
      - 'goes restart'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10
